#変更しないでください。
gateway: "ws://vpn.rezxis.net:2020"
#/thirdparty statusで出るkeyを入れてください。
token: "token"
#サーバーメニューに表示、非表示の指定です。
visible: true
#サーバーメニューに使うiconを指定できます。
icon: "EMERALD_BLOCK"
#投票されたときに実行されます。
vote: "/tell [player] thanks you"
#指示されたときのみ
laddr: ""
